### ISSUE TITLE
for new users

### ISSUE THREAD

**Issue by sfg2017** [admpro/Library_Management_System#1]
just struggle for a better life and hard work, boy.

**Comment by litebeyond123** [comment]
oh, thx

**Comment by sfg2017** [comment]
you are welcome, alice

**Comment by sfg2017** [comment]
oh, test,test

**Comment by sfg2017** [comment]
hello,world

**Comment by sfg2017** [comment]
oh my god, what are you doing

**Comment by sfg2017** [comment]
hhhhhhhhhhhhhhhhhh
fjeifjeif'eg
ejgieojgieojg oij
fefefefjeifo

**Comment by litebeyond123** [comment]
sun flowers

**Comment by litebeyond123** [comment]
this is just a test, so please have a rest

ok

**Comment by litebeyond123** [comment]
update error code 404

**Comment by litebeyond123** [comment]
hey,boy 
i just wanna to say 
tomorrow is beautiful

**Comment by litebeyond123** [comment]
what? oh my god

**Comment by sfg2017** [comment]
but, what do you mean ?

**Comment by sfg2017** [comment]
may be  we can make a deal

**Comment by sfg2017** [comment]
socket
test
answer
final
test

**Comment by sfg2017** [comment]
see you 
are you ok 
fine
 thanks

**Comment by sfg2017** [comment]
banner

**Comment by litebeyond123** [comment]
test20180822 16:12

**Comment by litebeyond123** [comment]
oh my god

**Comment by litebeyond123** [comment]
see you man

**Comment by litebeyond123** [comment]
ppap fix

**Comment by sfg2017** [comment]
20180822 test test

**Comment by litebeyond123** [comment]
20180822 17:05 mail test messages

**Comment by sfg2017** [comment]
20180822 17:30 fail test messages

**Comment by litebeyond123** [comment]
I am doing better and better

**Comment by litebeyond123** [comment]
I have a pen, I have an apple

**Comment by litebeyond123** [comment]
but, it just flowers

**Comment by litebeyond123** [comment]
thank you sir, can you have a look ?

**Comment by litebeyond123** [comment]
test to send a message

**Comment by litebeyond123** [comment]
test, another test

**Comment by litebeyond123** [comment]
an error code 404. see you

**Comment by litebeyond123** [comment]
but, what do you mean?

**Comment by litebeyond123** [comment]
it is time to leave

**Comment by litebeyond123** [comment]
see you, later

**Comment by litebeyond123** [comment]
it says ie is not supported in github

**Comment by litebeyond123** [comment]
can you help me?

**Comment by sfg2017** [comment]
continue to notice, ok

**Comment by sfg2017** [comment]
dll fix for github

**Comment by sfg2017** [comment]
oh thank you

**Comment by litebeyond123** [comment]
it is time to have a rest

**Comment by litebeyond123** [comment]
are you ok ?

**Comment by litebeyond123** [comment]
test 20180904

**Comment by litebeyond123** [comment]
see you 20180904

**Comment by litebeyond123** [comment]
maby 20180904

**Comment by litebeyond123** [comment]
are you ok 20180905

**Comment by litebeyond123** [comment]
hello ,world 20180905 14 10

**Comment by litebeyond123** [comment]
next time to leave 20180906

**Comment by litebeyond123** [comment]
this is the comment of github test 2018/9/6 1:24

**Comment by litebeyond123** [comment]
bug, bug test 20180906 5:22

**Comment by litebeyond123** [comment]
test, test for 20180906 5:31

**Comment by litebeyond123** [comment]
but, i am still alive 20180906 5:48

**Comment by litebeyond123** [comment]
it is still useless, bug 5:51

**Comment by litebeyond123** [comment]
test end useless 20180906 5:55

**Comment by litebeyond123** [comment]
quickly, bob 2018/09/06 15:26

**Comment by litebeyond123** [comment]
last test 2018/9/6 21:22

**Comment by litebeyond123** [comment]
new test 2018/09/6 21:22

**Comment by litebeyond123** [comment]
guys, final test 2018/9/7 8:32

**Comment by litebeyond123** [comment]
it is unfair, you know 2018/9/7 8:35

**Comment by litebeyond123** [comment]
are you kidding ? 2018/9/7 8:37
zzzzzzzzzzzzzzzzzzzz

**Comment by litebeyond123** [comment]
test test 2018/9/7 8:39

**Comment by litebeyond123** [comment]
welcome, see you.

**Comment by litebeyond123** [comment]
have a nice day 2018/9/7 8:40

**Comment by litebeyond123** [comment]
test github comment 2018/9/8 10:59

**Comment by litebeyond123** [comment]
test github again

**Comment by litebeyond123** [comment]
test github 2018/9/8 11:20

**Comment by litebeyond123** [comment]
ban git comment 11:29

**Comment by litebeyond123** [comment]
it is time to learn 20180915 22:19

**Comment by litebeyond123** [comment]
new comment

**Comment by litebeyond123** [comment]
2018/9/19 test

**Comment by litebeyond123** [comment]
hjhjhj

**Comment by litebeyond123** [comment]
123456

**Comment by litebeyond123** [comment]
123456

**Comment by litebeyond123** [comment]
erererererre

**Comment by litebeyond123** [comment]
efererererer

**Comment by litebeyond123** [comment]
fefefefefefefef

**Comment by litebeyond123** [comment]
fefefef

**Comment by litebeyond123** [comment]
95279257

**Comment by litebeyond123** [comment]
fefeferere

**Comment by litebeyond123** [comment]
frfrfrfrfrf

**Comment by litebeyond123** [comment]
66666666

**Comment by litebeyond123** [comment]
666666666666666666666666

**Comment by litebeyond123** [comment]
admpro commented a minute ago   











66666666

**Comment by litebeyond123** [comment]
erererererererer

**Comment by litebeyond123** [comment]
6666666666666666666666666666666666

**Comment by litebeyond123** [comment]
efefefefef

**Comment by litebeyond123** [comment]
飞机飞机飞哦

**Comment by litebeyond123** [comment]
erererer

**Comment by litebeyond123** [comment]
ererererer

**Comment by litebeyond123** [comment]
fefefef

**Comment by litebeyond123** [comment]
2212121213

**Comment by litebeyond123** [comment]
34343434

**Comment by litebeyond123** [comment]
45454545

**Comment by litebeyond123** [comment]
999999999

**Comment by litebeyond123** [comment]
666666

**Comment by litebeyond123** [comment]
524242

**Comment by litebeyond123** [comment]
ervrgrgrgr

**Comment by litebeyond123** [comment]
upload fail
